# MD5: ed0a6928fd4e6d3b2057d9e29921384d
set(CFG_UPHY_CHIP_TYPE_PATH cs) 

if(${OBB_TEN_LLT_MODE} MATCHES "TEN_LLT_ON")
set(CFG_XTENSA_CORE_NR BB5000_NX) 

else()
set(CFG_XTENSA_CORE_NR BB5000v2_NX) 

endif()
set(CFG_XTENSA_SYSTEM_NR "$(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RH-2018.5-linux/$(CFG_XTENSA_CORE_NR)/config") 

set(CFG_TENSILICA_BUILDS_NR "$(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RH-2018.5-linux") 

set(CFG_TENSILICA_TOOLS_NR "$(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RH-2018.5-linux") 

set(LD_SCRIPT_PATH_NR modem/platform/dsp/kirin990_cs2/nr/$(CFG_UPHY_CHIP_TYPE_PATH)$(OBB_LPHY_LATE_TYPE_PATH)/lsp) 

set(LD_SCRIPT_NAME_NR mainlsp) 

set(LPHY_XTENSA_RULES_NR cc_tensilica5.0.5_rules_nr.mk) 

set(CFG_XTENSA_PREDICT_BUG YES) 

set(CFG_NPHY_DTCM_BASE 0xE3400000) 

set(CFG_NPHY_ITCM_BASE 0xE3500000) 

set(CFG_NPHY_DTCM_SIZE 0x80000) 

set(CFG_NPHY_ITCM_SIZE 0x0) 

set(CFG_NPHY_HL1C_DTCM_SIZE 0x80000) 

set(CFG_NPHY_LL1D_DTCM_SIZE 0x80000) 

set(CFG_NPHY_LL1U_DTCM_SIZE 0x80000) 

set(CFG_NPHY_SDR_DTCM_SIZE 0x80000) 

set(CFG_NPHY_L2M_BASE 0xE3600000) 

set(CFG_NPHY_L2M_SIZE 0x0) 

set(CFG_NPHY_L2C_BASE 0xE3680000) 

set(CFG_NPHY_L2C_SIZE 0x0) 

set(CFG_NPHY_MMB_BASE 0xF6800000) 

set(CFG_NPHY_MMB_SIZE 0x200000) 

set(CFG_NPHY_MMB_CODE_BASE 0xF6800000) 

set(CFG_NPHY_MMB_CODE_SIZE 0x18C000) 

set(CFG_NPHY_MMB_DATA_BASE $(CFG_NPHY_MMB_CODE_BASE) + $(CFG_NPHY_MMB_CODE_SIZE)) 

set(CFG_NPHY_MMB_DATA_SIZE $(CFG_NPHY_MMB_SIZE)-$(CFG_NPHY_MMB_CODE_SIZE)) 

set(CFG_NPHY_MMB_COMM_SDATA_BASE $(CFG_NPHY_MMB_DATA_BASE)) 

set(CFG_NPHY_MMB_COMM_SDATA_SIZE 0x4000) 

set(CFG_NPHY_MMB_USER_SDATA_BASE $(CFG_NPHY_MMB_COMM_SDATA_BASE) + $(CFG_NPHY_MMB_COMM_SDATA_SIZE)) 

set(CFG_NPHY_MMB_USER_SDATA_SIZE 0x70000) 

set(CFG_NPHY_MMB_USER_NC_SDATA_BASE $(CFG_NPHY_MMB_USER_SDATA_BASE)) 

set(CFG_NPHY_MMB_USER_NC_SDATA_SIZE 0xA000) 

set(CFG_NPHY_MMB_USER_EC_SDATA_BASE $(CFG_NPHY_MMB_USER_NC_SDATA_BASE) + $(CFG_NPHY_MMB_USER_NC_SDATA_SIZE)) 

set(CFG_NPHY_MMB_USER_EC_SDATA_SIZE 0x66000) 

set(CFG_NPHY_BOOT_REMAP_OFFSET 0x2000) 

if(${CFG_EMU_TYPE_EMU} MATCHES "FEATURE_ON")
set(CFG_NPHY_SRAM_BASE 0x20000) 

set(CFG_NPHY_SRAM_SIZE 0xe0000) 

set(CFG_NPHY_DDR_BASE $(CFG_NPHY_SRAM_BASE) + $(CFG_NPHY_SRAM_SIZE)) 

set(CFG_NPHY_DDR_SIZE 0x20000000) 

set(CFG_NPHY_DDR_NX_IMAGE_BASE $(CFG_NPHY_DDR_BASE)) 

set(CFG_NPHY_DDR_NX_IMAGE_SIZE 0x2000000) 

set(CFG_NPHY_DDR_NX_BOOT_BASE $(CFG_NPHY_DDR_NX_IMAGE_BASE) + $(CFG_NPHY_BOOT_REMAP_OFFSET)) 

set(CFG_NPHY_DDR_PDE_IMAGE_BASE $(CFG_NPHY_DDR_NX_IMAGE_BASE) + $(CFG_NPHY_DDR_NX_IMAGE_SIZE)) 

set(CFG_NPHY_DDR_PDE_IMAGE_SIZE 0x1000000) 

set(CFG_NPHY_DDR_CSI_IMAGE_BASE $(CFG_NPHY_DDR_PDE_IMAGE_BASE) + $(CFG_NPHY_DDR_PDE_IMAGE_SIZE)) 

set(CFG_NPHY_DDR_CSI_IMAGE_SIZE 0x800000) 

set(CFG_NPHY_DDR_LINK_BASE $(CFG_NPHY_DDR_CSI_IMAGE_BASE) + $(CFG_NPHY_DDR_CSI_IMAGE_SIZE)) 

set(CFG_NPHY_DDR_SCRATCH_BASE $(CFG_NPHY_DDR_LINK_BASE) + $(CFG_NPHY_DDR_LINK_SIZE)) 

set(CFG_NPHY_DDR_SCRATCH_SIZE 0x10000000) 

set(CFG_NPHY_DDR_SOCP_STUB_BUFF_BASE $(CFG_NPHY_DDR_SCRATCH_BASE) + $(CFG_NPHY_DDR_SCRATCH_SIZE)) 

set(CFG_NPHY_DDR_SOCP_STUB_BUFF_SIZE 0x800000) 

else()
set(CFG_NPHY_SRAM_BASE 0) 

set(CFG_NPHY_SRAM_SIZE 0) 

set(CFG_NPHY_DDR_BASE $(CFG_DDR_NRPHY_IMAGE_ADDR)) 

set(CFG_NPHY_DDR_SIZE $(CFG_DDR_NRPHY_IMAGE_SIZE)) 

set(CFG_NPHY_DDR_NX_IMAGE_BASE $(CFG_NPHY_DDR_BASE)) 

set(CFG_NPHY_DDR_NX_IMAGE_SIZE $(CFG_NPHY_DDR_SIZE)-$(CFG_NPHY_DDR_LINK_SIZE)) 

set(CFG_NPHY_DDR_NX_BOOT_BASE $(CFG_NPHY_DDR_NX_IMAGE_BASE) + $(CFG_NPHY_BOOT_REMAP_OFFSET)) 

set(CFG_NPHY_DDR_LINK_BASE $(CFG_NPHY_DDR_NX_IMAGE_BASE) + $(CFG_NPHY_DDR_NX_IMAGE_SIZE)) 

set(CFG_NPHY_DDR_SCRATCH_BASE $(CFG_DDR_SDR_NR_ADDR)) 

set(CFG_NPHY_DDR_SCRATCH_SIZE $(CFG_DDR_SDR_NR_SIZE)) 

endif()
set(CFG_NPHY_DDR_LINK_SIZE 0x200000) 

set(CFG_NPHY_DDR_LINK_NC_SIZE 0x100000) 

set(CFG_NPHY_DDR_LINK_EC_SIZE $(CFG_NPHY_DDR_LINK_SIZE)-$(CFG_NPHY_DDR_LINK_NC_SIZE)) 

set(CFG_NPHY_DDR_USER_NC_SDATA_BASE $(CFG_NPHY_DDR_LINK_BASE)) 

set(CFG_NPHY_DDR_USER_NC_SDATA_SIZE 0x100000) 

set(CFG_NPHY_TOTAL_IMG_SIZE ((NPHY_DTCM_SIZE) + (NPHY_ITCM_SIZE) + (NPHY_L2M_SIZE) + (NPHY_DDR_SIZE))) 

set(CFG_NPHY_FEATURE_HF_SWITCH FEATURE_OFF) 

set(CFG_NPHY_OM_RPT_ENABLED YES) 

set(CFG_NPHY_DESENSITIZATION_OFF YES) 

set(CFG_TL_RTT_TEST_ENABLED YES) 

set(CFG_NPHY_ASSERT_ENABLED YES) 

