# MD5: b6ccda60206751bdd778e1e04618427c
set(CFG_TENSILICA_BUILDS_HIFI "$(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RF-2015.3-linux") 

set(CFG_TENSILICA_TOOLS_HIFI "$(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RF-2015.3-linux") 

set(CFG_FEATURE_HIFI FEATURE_ON) 

set(CFG_FEATURE_HIFI_USE_ICC FEATURE_ON) 

set(CFG_MBB_HIFI_ENABLE_PACK_IMAGE YES) 

set(CFG_FEATURE_MBB_MODULE_AUDIO FEATURE_ON) 

set(CFG_FEATURE_VOICE_UP FEATURE_OFF) 

set(CFG_FEATURE_DTMF FEATURE_ON) 

set(CFG_FEATURE_VOICE_INBAND_DTMF_ELIMINATE FEATURE_ON) 

set(CFG_PLATFORM_CHIP_TYPE p532) 

