# MD5: 58aa64d3d7433a40611b0f7e4113829e
set(CFG_XTENSA_CORE_X_CACHE Phoenix_NX) 

set(CFG_XTENSA_CORE_X_SYSTEM "RH-2018.5") 

set(CFG_XTENSA_CORE "$(CFG_XTENSA_CORE_X_CACHE)") 

set(CFG_XTENSA_SYSTEM "$(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/$(CFG_XTENSA_CORE_X_SYSTEM)/$(CFG_XTENSA_CORE)/config") 

set(CFG_TENSILICA_BUILDS "$(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/$(CFG_XTENSA_CORE_X_SYSTEM)") 

set(CFG_TENSILICA_TOOLS "$(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/$(CFG_XTENSA_CORE_X_SYSTEM)") 

set(LD_SCRIPT_PATH modem/platform/dsp/kirin990_cs2/lr/$(OBB_LPHY_CHIP_TYPE_PATH)$(OBB_LPHY_LATE_TYPE_PATH)/lsp) 

set(LD_SCRIPT_NAME mainlsp) 

set(LPHY_XTENSA_RULES cc_tensilica5.0.5_rules_lr.mk) 

set(CFG_XTENSA_PREDICT_BUG YES) 

set(CFG_XTENSA_INST_PREFETCH_BUG NO) 

set(CFG_XTENSA_DATA_PREFETCH_BUG NO) 

set(CFG_LPHY_DTCM_BASE 0xE3400000) 

set(CFG_LPHY_ITCM_BASE 0xE3500000) 

set(CFG_LPHY_DTCM_SIZE 0xc0000) 

set(CFG_LPHY_ITCM_SIZE 0x80000) 

set(CFG_LPHY_L2M_BASE 0xE3680000) 

set(CFG_LPHY_L2M_SIZE 0x100000) 

set(CFG_LPHY_L2C_BASE 0xE3780000) 

set(CFG_LPHY_L2C_SIZE 0x80000) 

set(CFG_LPHY_SRAM_BASE 0x20000) 

set(CFG_LPHY_SRAM_SIZE 0xe0000) 

set(CFG_LPHY_DDR_BASE $(CFG_DDR_TLPHY_IMAGE_ADDR) + 0x10000) 

set(CFG_LPHY_DDR_SIZE 0x800000) 

set(CFG_LPHY_DDR_IMAGE_BASE $(CFG_LPHY_DDR_BASE)) 

set(CFG_LPHY_DDR_IMAGE_SIZE $(CFG_LPHY_DDR_SIZE)) 

set(CFG_LPHY_DDR_LINK_BASE $(CFG_LPHY_DDR_IMAGE_BASE) + $(CFG_LPHY_DDR_IMAGE_SIZE)) 

set(CFG_LPHY_DDR_LINK_SIZE (0x20000000-(LPHY_DDR_IMAGE_SIZE))) 

set(CFG_LPHY_TOTAL_IMG_SIZE ((LPHY_DTCM_SIZE) + (LPHY_ITCM_SIZE) + (LPHY_L2M_SIZE) + (LPHY_DDR_SIZE))) 

set(CFG_LPHY_SLT_DDR_BASE $(CFG_TLPHY_IMAGE_LOAD_ADDR_ATE)) 

set(CFG_LPHY_SLT_DDR_SIZE $(CFG_TLPHY_IMAGE_LOAD_SIZE_ATE)) 

set(CFG_CPHY_PUB_DTCM_BASE 0xe3486400) 

set(CFG_CPHY_PUB_ITCM_BASE 0xe3531000) 

set(CFG_CPHY_PRV_DTCM_BASE 0xe3486400) 

set(CFG_CPHY_PRV_ITCM_BASE 0xe3531000) 

set(CFG_CPHY_PUB_DTCM_SIZE 0x39C00) 

set(CFG_CPHY_PUB_ITCM_SIZE 0x2f000) 

set(CFG_CPHY_PRV_DTCM_SIZE 0x39C00) 

set(CFG_CPHY_PRV_ITCM_SIZE 0x2f000) 

set(CFG_LR_PHY_ARCH FEATURE_ON) 

set(CFG_LPHY_EICC_ENABLE YES) 

