# MD5: 2eec193dd383376e66998505a6ba7577
set(CFG_RFDSP_HARDMSG_M536 YES) 

set(CFG_RFIC_BOARD_TYPE_FPGA 0) 

set(CFG_RFIC_BOARD_TYPE_SFT 1) 

set(CFG_RFIC_BOARD_TYPE_ASIC 2) 

set(CFG_RFIC_BOARD_TYPE_SDAT 3) 

set(CFG_RFIC_BOARD_TYPE_PORTING 4) 

set(CFG_RFIC_CHIP_TYPE_6365 2) 

set(CFG_RFIC_CHIP_TYPE_6370 3) 

set(CFG_RFIC_CHIP_TYPE_6365CS 4) 

set(CFG_RFIC_CHIP_TYPE_6370CS 5) 

set(CFG_RFIC_SUB6G_XTENSA_CORE_SYSTEM "RG-2017.7") 

set(CFG_RFIC_SUB6G_XTENSA_CORE_CACHE Hi6365V100_Xten_fusion_P2) 

set(CFG_RFIC_SUB6G_LSP_SCRIPT_PATH "6365cs") 

set(CFG_RFIC_SUB6G_CHIP_TYPE_PATH "hi6365cs") 

set(CFG_RFIC_SUB6G_CHIP_TYPE RFIC_CHIP_TYPE_6365CS) 

set(CFG_RFIC_SUB6G_BOARD_TYPE RFIC_BOARD_TYPE_ASIC) 

set(CFG_RFIC_HF_XTENSA_CORE_SYSTEM "RG-2017.7") 

set(CFG_RFIC_HF_XTENSA_CORE_CACHE Hi6365V100_Xten_fusion_P2) 

set(CFG_RFIC_HF_LSP_SCRIPT_PATH "6370cs") 

set(CFG_RFIC_HF_CHIP_TYPE_PATH "hi6370cs") 

set(CFG_RFIC_HF_CHIP_TYPE RFIC_CHIP_TYPE_6370CS) 

set(CFG_RFIC_HF_BOARD_TYPE RFIC_BOARD_TYPE_ASIC) 

set(CFG_RFIC_BOARD_TYPE RFIC_BOARD_TYPE_ASIC) 

set(CFG_NXP_COMMON_STARTUP_DTCM_BASE 0xe3463f00) 

set(CFG_FEATURE_TWO_RFDSP_BIN FEATURE_OFF) 

set(CFG_FEATURE_SUPPORT_RFIC1 FEATURE_OFF) 

set(CFG_FEATURE_EASYRF FEATURE_ON) 

set(CFG_RFDSP_TRACE_MEM_SIZE 2048) 

set(CFG_FEATURE_EMU_TYPE_WHOLE NO) 

