# MD5: 901a4be876c6da2033647786bb4c66f8
set(CFG_FEATURE_IMS FEATURE_ON) 

set(CFG_FEATURE_LTE_R11 FEATURE_ON) 

set(CFG_FEATURE_LTE_R13 FEATURE_ON) 

set(CFG_FEATURE_LTE_R14 							 FEATURE_ON) 

set(CFG_FEATURE_LTE_MBMS FEATURE_OFF) 

set(CFG_FEATURE_LTE_CDMA_R11 FEATURE_OFF) 

set(CFG_FEATURE_PTM FEATURE_ON) 

set(CFG_FEATURE_BALONG_CL FEATURE_ON) 

set(CFG_FEATURE_LTE_CAT_PART_R11 YES) 

set(CFG_TL_PS_MAX_TRCH_NUM_8 YES) 

set(CFG_FEATURE_LPP FEATURE_ON) 

set(CFG_FEATURE_5G_LPP FEATURE_OFF) 

set(CFG_FEATURE_TDS_WCDMA_DYNAMIC_LOAD FEATURE_OFF) 

set(CFG_FEATURE_CSG FEATURE_ON) 

set(CFG_FEATURE_DFS_SYNC FEATURE_OFF) 

set(CFG_FEATURE_VERSION_V8 FEATURE_OFF) 

set(CFG_FEATURE_DCX0_TLHPA_WRITE_PHY_NV FEATURE_ON) 

set(CFG_FEATURE_CSS_CLOUD_MEMORY_IMPROVE FEATURE_ON) 

set(CFG_FEATURE_CSS_RAT_RECOGNIZE FEATURE_ON) 

set(CFG_FEATURE_MODEM1_SUPPORT_LTE FEATURE_ON) 

set(CFG_FEATURE_MEM_DECREASE FEATURE_OFF) 

set(CFG_FEATURE_M2M FEATURE_ON) 

set(CFG_FEATURE_CSS_DSDS_START_BGS FEATURE_OFF) 

set(CFG_FEATURE_KIRIN970_ES_VERSION FEATURE_OFF) 

set(CFG_FEATURE_LL2_SUPPORT_LLRAM_DL_TB FEATURE_ON) 

set(CFG_FEATURE_SUPPORT_SSP10 FEATURE_OFF) 

set(CFG_FEATURE_MEMORY_REDUCE FEATURE_OFF) 

set(CFG_FEATURE_LTE_JAM_DET FEATURE_OFF) 

set(CFG_FEATURE_LTE_ASN_CUT FEATURE_ON) 

set(CFG_FEATURE_LL2_SPECIAL_VERSION FEATURE_OFF) 

set(CFG_FEATURE_IQI FEATURE_OFF) 

set(CFG_FEATURE_LMAC_LPHY_EPDCCH_CR FEATURE_OFF) 

set(CFG_FEATURE_UL_HCODE FEATURE_OFF) 

set(CFG_FEATURE_LL2_SUPPORT_DSDSV3 FEATURE_ON) 

set(CFG_FEATURE_LTE_R12 FEATURE_ON) 

set(CFG_FEATURE_LTE_DC FEATURE_ON) 

set(CFG_FEATURE_LTE_LAA                 			 FEATURE_ON) 

set(CFG_FEATURE_IMS_USSD FEATURE_ON) 

set(CFG_FEATURE_IMS_SMS FEATURE_ON) 

set(CFG_FEATURE_IMS_VOWIFI FEATURE_ON) 

set(CFG_FEATURE_IMS_URSP FEATURE_ON) 

set(CFG_FEATURE_LTE_RLC_EXT_SN FEATURE_OFF) 

set(CFG_FEATURE_SUPPORT_5G_RTT_TIME_DOMAIN_BBIT FEATURE_OFF) 

set(CFG_FEATURE_LTE_R15 FEATURE_ON) 

set(CFG_FEATURE_LTE_ENDC FEATURE_ON) 

set(CFG_FEATURE_SUSPECTX_EMC_OPTIMIZE_SRCH FEATURE_ON) 

set(CFG_FEATURE_LL2_SUPPORT_ROHC_PROFILE_6 FEATURE_ON) 

set(CFG_FEATURE_LTE_SUPPORT_NPDCP FEATURE_ON) 

set(CFG_FEATURE_NEW_LUP_MEM FEATURE_ON) 

set(CFG_FEATURE_LTE_UL_256QAM FEATURE_OFF) 

set(CFG_FEATURE_LRRC_PRINT_CUT_DEFAULT_ON				 FEATURE_ON) 

set(CFG_FEATURE_LRRC_VOS_PRINT_CUT_DEFAULT_OFF			 FEATURE_OFF) 

set(CFG_FEATURE_LMAC_LPHY_R14_CR FEATURE_ON) 

set(CFG_FEATURE_PSUP_MEM_DEBUG FEATURE_ON) 

set(CFG_FEATURE_NRL2_SLEEP FEATURE_ON) 

set(CFG_FEATURE_LL2_SUPPORT_9_UL_HARQ_NUM FEATURE_ON) 

set(CFG_FEATURE_NL2_BIT_SWITCH FEATURE_OFF) 

set(CFG_FEATURE_EXTRA_MODEM_MODE FEATURE_OFF) 

set(CFG_FEATURE_LTE_DT FEATURE_ON) 

set(CFG_FEATURE_LRRC_CLOUD_CA_1024 FEATURE_ON) 

set(CFG_PROTOL_STACK_ENG YES) 

set(CFG_TLL2_ENG_VERSION YES) 

set(CFG_FEATURE_LTE_5010 FEATURE_OFF) 

set(CFG_FEATURE_LL2_SUPPORT_UL_DYN_SKIP FEATURE_ON) 

set(CFG_FATURE_LL2_SUPPORT_NR_PHR FEATURE_ON) 

set(CFG_FEATURE_LTE_UECAP FEATURE_ON) 

set(CFG_FEATURE_LTE_REDUCE_MEASURE_16AFRAN FEATURE_ON) 

set(CFG_FEATURE_HIFI_MANAGE FEATURE_OFF) 

set(CFG_LTE_MAX_PER_CLOUD_CA_PLMN_NUM 1024) 

set(CFG_FEATURE_APN_BASED_BO_TIMER_PARA_RPT FEATURE_ON) 

set(CFG_FEATURE_NSSAI_BASED_BO_TIMER_PARA_RPT FEATURE_ON) 

