# MD5: 3a53ed8ee69a5d2322461b752909e9c2
set(CFG_FEATURE_ON 1) 

set(CFG_FEATURE_OFF 0) 

set(CFG_FEATURE_MLOG FEATURE_ON) 

set(CFG_FEATURE_DT FEATURE_ON) 

if(${EMU_TYPE_ESLPS} MATCHES "FEATURE_ON")
set(CFG_FEATURE_NPHY_STUB_ESL FEATURE_ON) 

else()
set(CFG_FEATURE_NPHY_STUB_ESL FEATURE_OFF) 

endif()
if(${EMU_TYPE_ESL} MATCHES "FEATURE_ON")
set(CFG_FEATURE_NRRC_EMU_ESL FEATURE_ON) 

else()
set(CFG_FEATURE_NRRC_EMU_ESL FEATURE_OFF) 

endif()
set(CFG_FEATURE_NL2_MAA_ALLOC FEATURE_ON) 

set(CFG_NR_PROTOL_STACK_ENG YES) 

set(CFG_FEATURE_NR_SEC_DISABLE FEATURE_ON) 

set(CFG_FEATURE_NSSAI_AUTH FEATURE_ON) 

set(CFG_FEATURE_OPRDEF_CATEGORY FEATURE_ON) 

set(CFG_FEATURE_LADN FEATURE_ON) 

set(CFG_NR_MAX_SERVING_CC_NUM 1) 

set(CFG_NR_MAX_UL_SERVING_CC_NUM 1) 

set(CFG_NR_MAX_CG_NUM 1) 

set(CFG_FEATURE_MODEM1_SUPPORT_NR FEATURE_OFF) 

set(CFG_FEATURE_NL2_1CC_MEM FEATURE_ON) 

set(CFG_NR_MAX_PER_PLMN_NRSA_BC_NUM 128) 

set(CFG_NR_MAX_PER_PLMN_ENDC_BC_NUM 512) 

set(CFG_NR_MAX_PER_PLMN_NRDC_BC_NUM 16) 

set(CFG_NR_MAX_PER_PLMN_TXSW_NRSA_BC_NUM 64) 

set(CFG_NR_MAX_PER_PLMN_TXSW_ENDC_BC_NUM 128) 

set(CFG_NR_MAX_NRSA_BC_NUM 512) 

set(CFG_NR_MAX_ENDC_BC_NUM 1024) 

set(CFG_NR_MAX_NRDC_BC_NUM 16) 

set(CFG_NR_MAX_TXSW_NRSA_BC_NUM 64) 

set(CFG_NR_MAX_TXSW_ENDC_BC_NUM 128) 

set(CFG_NR_MAX_NR_FSD_OTHER_PARA_NUM 128) 

set(CFG_NR_MAX_NR_FSU_OTHER_PARA_NUM 128) 

set(CFG_NR_MAX_NR_FSD_PARA_NUM 256) 

set(CFG_NR_MAX_NR_FSU_PARA_NUM 256) 

set(CFG_NR_MAX_LTE_FSD_PARA_NUM 256) 

set(CFG_NR_MAX_LTE_FSU_PARA_NUM 256) 

set(CFG_NR_MAX_NR_FSPC_DL_NUM 128) 

set(CFG_NR_MAX_NR_FSPC_UL_NUM 128) 

set(CFG_NR_MAX_SIMPLE_FSC_NUM_PER_SUPER_FSC 16) 

set(CFG_NR_MAX_FSC_NUM 128) 

set(CFG_NR_MAX_PER_BC_NR_BAND_NUM 2) 

set(CFG_NR_MAX_PER_BC_LTE_BAND_NUM 5) 

set(CFG_NR_MAX_PER_BC_BAND_NUM 6) 

set(CFG_NR_MAX_PER_BAND_CC_NUM 6) 

set(CFG_FEATURE_NR_R16 FEATURE_OFF) 

set(CFG_FEATURE_NR_R16_TODO FEATURE_OFF) 

set(CFG_FEATURE_ENDC FEATURE_ON) 

set(CFG_FEATURE_HMS_KIT FEATURE_ON) 

