# MD5: d721bac6ee9a27a393f8ba90f2638b57
set(CFG_BBIC_CHIP_ES YES) 

set(CFG_ZSP_DSP_CHIP_BB_TYPE		 52) 

set(CFG_NV_VERSION kirin990_cs2) 

set(CFG_ZSP_DSP_PRODUCT_FORM		 4) 

set(CFG_BOARD ASIC) 

set(CFG_UPHY_BOARD_TYPE 2) 

set(CFG_FEATURE_TEMP_MULTI_MODE_LP FEATURE_ON) 

set(CFG_FEATURE_GSM_SDR FEATURE_ON) 

set(CFG_FEATURE_GSM_SDR_DAIC FEATURE_ON) 

set(CFG_FEATURE_GSM_WHOLE_SDR		 FEATURE_ON) 

set(CFG_FEATURE_XBBE16_NEW_MAIL		 FEATURE_ON) 

set(CFG_FEATURE_SRAM_400K FEATURE_OFF) 

set(CFG_FEATURE_EXTERNAL_32K_CLK		 FEATURE_ON) 

set(CFG_FEATURE_SOCP_ON_DEMAND			 FEATURE_OFF) 

set(CFG_FEATURE_TAS				 FEATURE_ON) 

if(${CFG_EMU_TYPE_ESLPS} MATCHES "FEATURE_ON")
set(CFG_FEATURE_NPHY_ESLPS YES) 

endif()
if(${CFG_EMU_TYPE_ESL} MATCHES "FEATURE_ON")
set(CFG_FEATURE_NPHY_ESL YES) 

endif()
set(CFG_FEATURE_VIRTUAL_BAND			 FEATURE_ON) 

set(CFG_FEATURE_HI6363                		 FEATURE_ON) 

set(CFG_FEATURE_RTT_TEST FEATURE_ON) 

set(CFG_FEATURE_RTT_RANDOM_TEST FEATURE_OFF) 

set(CFG_FEATURE_GUTLC_ONE_DSP FEATURE_ON) 

set(CFG_FEATURE_NX_CORE_OPEN FEATURE_ON) 

set(CFG_FEATURE_CSDR FEATURE_ON) 

set(CFG_FEATURE_HITUNE FEATURE_OFF) 

set(CFG_CPHY_PUB_DTCM_GLB_MINUS_LOCAL	 0x00800000) 

set(CFG_GUC_RTT_TEST_ENABLED YES) 

set(CFG_PHY_CBT_ENABLED YES) 

set(CFG_MODEM_GUPHY_LTO YES) 

set(CFG_UPHY_NSCS_CTRL YES) 

