/*
 * Huawei Technologies Sweden AB (C), 2001-2019
 * @author    Automatically generated by DAISY
 * @version
 * @date      2017-04-28 15:27:40
 * @file
 * @brief
 * @copyright Huawei Technologies Sweden AB
 */
#ifndef PAM_MID_INTERFACE_H
#define PAM_MID_INTERFACE_H

/*
 * 1. Other files included
*/
#include "vos.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
#pragma pack(push, 4)

/*
 * 2. Macro definitions
 */

#define  BBA_FID_CAL   DSP_FID_BBA_CAL
#define  BBA_FID_CALC  DSP_FID_BBA_CALC

#define  BBA_PID_CCBT  CCPU_PID_CBT
#define  BBA_PID_CAL   DSP_PID_BBA_CAL
#define  BBA_PID_CALC  DSP_PID_BBA_CALC

/*
 * 3. Enumerations declarations
 */

/*
 * 7. OTHER declarations
 */

/*
 * 8. Global  declaration
 */

/*
 * 9. Function declarations
 */

#pragma pack(pop)

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif

