

/*****************************************************************************
  1 头文件包含
*****************************************************************************/
#include "ChrEventIDComm.h"

#ifdef __cplusplus
  #if __cplusplus
  extern "C"{
  #endif
#endif

/*****************************************************************************
  2 全局变量声明
*****************************************************************************/

#if (FEATURE_ON == FEATURE_PTM)

/* GAS 非关联直通事件定义集合 */
int g_aulGASAbosulteEvent[][2]=
{
    {GAS_STATISTIC_INFO_COLLECTION_EVENTID, GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU_ALARMID},
    {GAS_STATISTIC_INFO_COLLECTION_EVENTID, GAS_CUSTOM_C1_CELL_CHR_RPT_STRU_ALARMID},

    {GAS_STATISTIC_INFO_COLLECTION_EVENTID, GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU_ALARMID},

    {GAS_STATISTIC_INFO_COLLECTION_EVENTID, GAS_ERR_LOG_EVT_GSM_CELL_CALL_TIMES_RPT_STRU_ALARMID},

    {GAS_STATISTIC_INFO_COLLECTION_EVENTID, GAS_AP_G2L_RESEL_HIT_STATISTICS_STRU_ALARMID},

    {GAS_STATISTIC_INFO_COLLECTION_EVENTID, GAS_AP_G2L_PING_PONG_RESTRAIN_RECORD_RPT_STRU_ALARMID},
    {GAS_STATISTIC_INFO_COLLECTION_EVENTID, GAS_AP_GSM_AIR_MSG_ABNORMAL_STRU_ALARMID},
    {GAS_STATISTIC_INFO_COLLECTION_EVENTID, GAS_AP_GU_PING_PONG_RESTRAIN_RECORD_RPT_STRU_ALARMID}
};

/* WAS 非关联直通事件定义集合 */
int g_aulWASAbosulteEvent[][2]=
{
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_RRC_ACCESS_LONG_CHR_RPT_STRU_ALARMID},
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU_ALARMID},
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU_ALARMID},
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_W2W_RESEL_SLOW_CHR_RPT_STRU_ALARMID},
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_NET_WORK_FEATURE_CHR_RPT_STRU_ALARMID},
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_DCH_TRIGGER_CU_CHR_RPT_STRU_ALARMID},
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_CS_END_CESSION_NOTIFY_CHR_RPT_STRU_ALARMID},
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_UL_PINGPONG_RESTRAIN_CHR_RPT_STRU_ALARMID},
    {WAS_STATISTIC_INFO_COLLECTION_EVENTID, WAS_RNC_RELOC_FAIL_CHR_RPT_STRU_ALARMID}
};

/* 资源核查事件 */
int g_aulRadioResourceCheckEvent[][2]=
{
    {PS_RADIO_RESOURCE_CHECK_EVENTID, GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID},
    {PS_RADIO_RESOURCE_CHECK_EVENTID, CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU_ALARMID},
#if (FEATURE_ON == FEATURE_UE_MODE_CDMA)
    {PS_RADIO_RESOURCE_CHECK_EVENTID, CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID},
    {PS_RADIO_RESOURCE_CHECK_EVENTID, CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID},
#endif
    {PS_RADIO_RESOURCE_CHECK_EVENTID, GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID},
    {PS_RADIO_RESOURCE_CHECK_EVENTID, WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID},
    /*Add by lilin 资源核查CHR 2017-3-13 begin*************/
    {PS_RADIO_RESOURCE_CHECK_EVENTID, TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU_ALARMID},
    /*Add by lilin 资源核查CHR 2017-3-13 end*************/
    {PS_RADIO_RESOURCE_CHECK_EVENTID,LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU_ALARMID},
    {PS_RADIO_RESOURCE_CHECK_EVENTID,NRRC_CHR_DIRECT_RADIO_RES_CHECK_STRU_ALARMID},
};

/* TRRC 非关联直通事件定义集合 */
int g_aulTRRCAbosulteEvent[][2]=
{
    {TRRC_STATISTIC_INFO_COLLECTION_EVENTID, TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU_ALARMID},
    {TRRC_STATISTIC_INFO_COLLECTION_EVENTID, TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU_ALARMID },
    {TRRC_STATISTIC_INFO_COLLECTION_EVENTID, TRRC_CS_CALL_EST_CNF_INFO_STRU_ALARMID},
    {TRRC_STATISTIC_INFO_COLLECTION_EVENTID, TRRC_CS_CALL_CONN_REQ_INFO_STRU_ALARMID},
    {TRRC_STATISTIC_INFO_COLLECTION_EVENTID, TRRC_CS_CALL_AIRMSG_INFO_STRU_ALARMID},
    {TRRC_STATISTIC_INFO_COLLECTION_EVENTID, TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU_ALARMID},
};

/* TMAC 非关联直通事件定义集合 */
int g_aulTMACbosulteEvent[][2]=
{

};

/* LRRC 统计1 非关联直通事件定义集合 */
int g_aulLRRCStatictic1Event[][2]=
{
    {LRRC_STATISTIC1_INFO_COLLECTION_EVENTID, LRRC_OM_UE_CAP_FALL_REPORT_STRU_ALARMID},
    {LRRC_STATISTIC1_INFO_COLLECTION_EVENTID, LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU_ALARMID},

};

/* LRRC 统计2 非关联直通事件定义集合 */
int g_aulLRRCStatictic2Event[][2]=
{

};

/* LL2 统计1 非关联直通事件定义集合 */
int g_aulLL2StaticticEvent[][2]=
{
    {LL2_STATISTIC_INFO_COLLECTION_EVENTID, LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU_ALARMID},
};

/* Volte自诊断事件 */
int g_aulLRRCVolteFaultAutoAnIndEvent[][2]=
{
    {LRRC_VOLTE_FAULT_AUTOAN_IND_EVENTID, LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU_ALARMID},
};

int g_aulLRRCVolteStatIndEvent[][2]=
{
    {LPS_VOLTE_STAT_IND_EVENTID, LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU_ALARMID},
};



/* LNAS 统计 非关联直通事件定义集合 */
int g_aulLNASStaticticEvent[][2]=
{
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_SMC_FAIL_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_SWITCH_APN_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU_ALARMID},

    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_RF_OCCUPY_MODEM1_TAU_STRU_ALARMID},
	{LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_REATTACH_PUNISH_CHR_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_DEEP_GAME_CHR_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_ATTACH_TAU_FAIL_MAXTIMES_CHR_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_ESM65_CHR_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_ESCAPE_CHR_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_LCSLPP_LEN_CHR_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_AIR_COMPATI_CHR_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ERABM_ERR_INFO_BEAR_ACT_WITHOUT_DRB_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_HO_WITHIN_TAU_PROCESS_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_LMM_OM_DL_NASCOUNT_ERR_CHR_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_BEARER_STATUS_INCONSISTENT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_REPEATEDLY_CONN_RECOVER_TAU_EFFECT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_RELEASE_SIGNAL_BEAR_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_ESCAPE_DESCEND_CAP_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_ROBUST_OPTIMIZATION_STATISTICS_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_CHANGE_NULL_APN_OPT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_LRRC_SMC_FAIL_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_5G_ESCAPE_DESCEND_CAP_INFO_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_COMPATIBILITY_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_ESM_ERR_INFO_ESM_STATUS_NOT_EQ_LMM_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_OPTIMIZATION_STATISTICS_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_INITIATE_TAU_OPTIMIZATION_STATISTICS_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_NR_EST_FAIL_EVENT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_IMPLICIT_DETACH_EMC_REDIAL_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_IMSA_ERR_INFO_MEDIA_PDP_LOST_EVENT_STRU_ALARMID},
    {LNAS_STATISTIC_INFO_COLLECTION_EVENTID, LNAS_EMM_ERR_INFO_N2L_HO_ABNORMAL_REL_STATISTICS_STRU_ALARMID}
};


/* GUNAS 非关联直通事件定义集合 */
int g_aulGUCNASAbosulteEvent[][2]=
{
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_SEARCHED_PLMN_INFO_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_SILENT_SMS_INFO_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_APS_PS_CALL_ENTITY_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_SRVCC_TIFLAG_ERR_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_RECEIVE_SMS_IN_ANTI_ATTACK_INFO_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_SMS_ANTI_ATTACK_INFO_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_READ_6FAD_USIM_FILE_ABNORMAL_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_NRMM_DECODE_MSG_ERR_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_NRMM_ESCAPE_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_NRMM_REG_ABNORMAL_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_NRMM_COMPATIBILITY_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_NRMM_REG_PROC_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_PCF_DECODE_MSG_ERR_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_NRSM_DECODE_MSG_ERR_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_NRSM_COMPATIBILITY_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, NRNAS_NRSM_AIR_MSG_RETRANSMIT_CHR_RPT_STRU_ALARMID},
    {GUNAS_STATISTIC_INFO_COLLECTION_EVENTID, GUNAS_AUTH_TYPE_ADAPTATION_CHR_RPT_STRU_ALARMID},
};

/* NRRC 非关联直通事件定义集合 */
int g_aulNRRCAbosulteEvent[][2]=
{
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_OTA_CHECK_FAIL_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_OUT_OF_SYNC_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_RA_FAIL_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_BAND_CNT_OVER_LMT_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_NW_PARA_ABNORMAL_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_EXTREME_SCENE_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_HPS_RPT_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_BAD_CELL_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_UECAP_ENQ_ABNORMAL_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_ASN_ENCODE_FAIL_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_UECAP_PROC_ERROR_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_OBTAION_UECAP_SRC_DATA_ERROR_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_UECAP_NW_ACT_ABNORMAL_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_UNEXP_MSG_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_CONTINUAL_REEST_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_N2L_EPSFB_STRU_ALARMID},
    {NRRC_STATISTIC_INFO_COLLECTION_EVENTID, NRRC_CHR_DIRECT_L2N_REDIR_FAIL_STRU_ALARMID}
};
#endif

/*****************************************************************************
  3 函数申明
*****************************************************************************/


#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif

