#include "ChrCommConvert.h"
#include "ChrEventIDComm.h"
#if (FEATURE_ON == FEATURE_UE_MODE_CDMA)
STRUCT_DESC g_CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = { CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID, 136};
STRUCT_DESC g_CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = { CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID, 136};
STRUCT_DESC g_CAS_ERRORLOG = { CAS_ERRORLOG_ALARMID_BUTT, 0};
#endif
STRUCT_DESC g_GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU = { GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU_ALARMID, 244};
STRUCT_DESC g_GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = { GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID, 106};
STRUCT_DESC g_GAS_CUSTOM_C1_CELL_CHR_RPT_STRU = { GAS_CUSTOM_C1_CELL_CHR_RPT_STRU_ALARMID, 164};
STRUCT_DESC g_GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU = { GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU_ALARMID, 28};
STRUCT_DESC g_GAS_ERR_LOG_EVT_GSM_CELL_CALL_TIMES_RPT_STRU = { GAS_ERR_LOG_EVT_GSM_CELL_CALL_TIMES_RPT_STRU_ALARMID, 244};
STRUCT_DESC g_GAS_ERRORLOG = { GAS_ERRORLOG_ALARMID_BUTT, 0};
STRUCT_DESC g_GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = { GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID, 304};
STRUCT_DESC g_GUNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU = { GUNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU_ALARMID, 164};
STRUCT_DESC g_GUNAS_RECEIVE_SMS_IN_ANTI_ATTACK_INFO_CHR_RPT_STRU = { GUNAS_RECEIVE_SMS_IN_ANTI_ATTACK_INFO_CHR_RPT_STRU_ALARMID, 20};
STRUCT_DESC g_GUNAS_SMS_ANTI_ATTACK_INFO_CHR_RPT_STRU = { GUNAS_SMS_ANTI_ATTACK_INFO_CHR_RPT_STRU_ALARMID, 20};
STRUCT_DESC g_GUCNAS_ERRORLOG = { GUCNAS_ERRORLOG_ALARMID_BUTT, 0};
STRUCT_DESC g_TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU = { TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU_ALARMID, 32};
STRUCT_DESC g_TRRC_OOS_INFO_STRU = { TRRC_OOS_INFO_STRU_ALARMID, 40};
STRUCT_DESC g_TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU = { TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU_ALARMID, 100};
STRUCT_DESC g_TRRC_CS_CALL_EST_CNF_INFO_STRU = { TRRC_CS_CALL_EST_CNF_INFO_STRU_ALARMID, 36};
STRUCT_DESC g_TRRC_CS_CALL_CONN_REQ_INFO_STRU = { TRRC_CS_CALL_CONN_REQ_INFO_STRU_ALARMID, 48};
STRUCT_DESC g_TRRC_CS_CALL_AIRMSG_INFO_STRU = { TRRC_CS_CALL_AIRMSG_INFO_STRU_ALARMID, 36};
STRUCT_DESC g_TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU = { TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU_ALARMID, 44};
STRUCT_DESC g_TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU = { TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU_ALARMID, 0};
STRUCT_DESC g_TRRC_ERRORLOG = { TRRC_ERRORLOG_ALARMID_BUTT, 0};
STRUCT_DESC g_LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU = { LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU_ALARMID, 1712};
STRUCT_DESC g_LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU = { LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU_ALARMID, 576};
STRUCT_DESC g_LRRC_OM_UE_CAP_FALL_REPORT_STRU = { LRRC_OM_UE_CAP_FALL_REPORT_STRU_ALARMID, 40};
STRUCT_DESC g_LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU = { LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU_ALARMID, 36};
STRUCT_DESC g_LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU = { LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU_ALARMID, 724};
STRUCT_DESC g_LRRC_ERRORLOG = { LRRC_ERRORLOG_ALARMID_BUTT, 0};
STRUCT_DESC g_TLL2_OOS_INFO_STRU = { TLL2_OOS_INFO_STRU_ALARMID, 4};
STRUCT_DESC g_LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU = { LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU_ALARMID, 260};
STRUCT_DESC g_TLL2_ERRORLOG = { TLL2_ERRORLOG_ALARMID_BUTT, 0};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU = { LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU = { LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU_ALARMID, 120};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU = { LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU = { LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU_ALARMID, 0};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU = { LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU_ALARMID, 60};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU = { LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU = { LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU = { LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU = { LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU = { LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_ALARMID, 60};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_SMC_FAIL_STRU = { LNAS_EMM_ERR_INFO_SMC_FAIL_STRU_ALARMID, 56};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU = { LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU_ALARMID, 20};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU = { LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU_ALARMID, 52};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU = { LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU = { LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU = { LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_SWITCH_APN_STRU = { LNAS_ESM_ERR_INFO_SWITCH_APN_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU = { LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_ALARMID, 60};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU = { LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU = { LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU = { LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU = { LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU = { LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU_ALARMID, 5};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU = { LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU = { LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU_ALARMID, 0};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU = { LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU_ALARMID, 0};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU = { LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU = { LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU = { LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU = { LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU = { LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU = { LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU = { LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU = { LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU = { LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU = { LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU_ALARMID, 48};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU = { LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU = { LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU = { LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU_ALARMID, 12};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU = { LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU = { LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_RF_OCCUPY_MODEM1_TAU_STRU = { LNAS_EMM_ERR_INFO_RF_OCCUPY_MODEM1_TAU_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_REATTACH_PUNISH_CHR_STRU = { LNAS_EMM_ERR_INFO_REATTACH_PUNISH_CHR_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_DEEP_GAME_CHR_INFO_STRU = { LNAS_EMM_ERR_INFO_DEEP_GAME_CHR_INFO_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_ATTACH_TAU_FAIL_MAXTIMES_CHR_STRU = { LNAS_EMM_ERR_INFO_ATTACH_TAU_FAIL_MAXTIMES_CHR_STRU_ALARMID, 72};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_ESM65_CHR_INFO_STRU = { LNAS_ESM_ERR_INFO_ESM65_CHR_INFO_STRU_ALARMID, 164};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_ESCAPE_CHR_INFO_STRU = { LNAS_EMM_ERR_INFO_ESCAPE_CHR_INFO_STRU_ALARMID, 280};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_LCSLPP_LEN_CHR_INFO_STRU = { LNAS_ESM_ERR_INFO_LCSLPP_LEN_CHR_INFO_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_AIR_COMPATI_CHR_INFO_STRU = { LNAS_ESM_ERR_INFO_AIR_COMPATI_CHR_INFO_STRU_ALARMID, 68};
STRUCT_DESC g_LNAS_ERABM_ERR_INFO_BEAR_ACT_WITHOUT_DRB_INFO_STRU = { LNAS_ERABM_ERR_INFO_BEAR_ACT_WITHOUT_DRB_INFO_STRU_ALARMID, 16};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_HO_WITHIN_TAU_PROCESS_INFO_STRU = { LNAS_EMM_ERR_INFO_HO_WITHIN_TAU_PROCESS_INFO_STRU_ALARMID, 16};
STRUCT_DESC g_LNAS_LMM_OM_DL_NASCOUNT_ERR_CHR_STRU = { LNAS_LMM_OM_DL_NASCOUNT_ERR_CHR_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_RELEASE_SIGNAL_BEAR_STRU = { LNAS_IMSA_ERR_INFO_RELEASE_SIGNAL_BEAR_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_BEARER_STATUS_INCONSISTENT_STRU = { LNAS_ESM_ERR_INFO_BEARER_STATUS_INCONSISTENT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_REPEATEDLY_CONN_RECOVER_TAU_EFFECT_STRU = { LNAS_EMM_ERR_INFO_REPEATEDLY_CONN_RECOVER_TAU_EFFECT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_ESCAPE_DESCEND_CAP_INFO_STRU = { LNAS_EMM_ERR_INFO_ESCAPE_DESCEND_CAP_INFO_STRU_ALARMID, 20};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_ROBUST_OPTIMIZATION_STATISTICS_INFO_STRU = { LNAS_EMM_ERR_INFO_ROBUST_OPTIMIZATION_STATISTICS_INFO_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_CHANGE_NULL_APN_OPT_STRU = { LNAS_ESM_ERR_INFO_CHANGE_NULL_APN_OPT_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_LRRC_SMC_FAIL_CHR = { LNAS_EMM_ERR_INFO_LRRC_SMC_FAIL_STRU_ALARMID, 52};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_5G_ESCAPE_DESCEND_CAP_INFO_STRU = { LNAS_ESM_ERR_INFO_5G_ESCAPE_DESCEND_CAP_INFO_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_COMPATIBILITY_STRU = { LNAS_EMM_ERR_INFO_COMPATIBILITY_STRU_ALARMID, 8};
STRUCT_DESC g_LNAS_ESM_ERR_INFO_ESM_STATUS_NOT_EQ_LMM_STRU = { LNAS_ESM_ERR_INFO_ESM_STATUS_NOT_EQ_LMM_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_OPTIMIZATION_STATISTICS_STRU = { LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_OPTIMIZATION_STATISTICS_STRU_ALARMID, 16};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_INITIATE_TAU_OPTIMIZATION_STATISTICS_STRU = { LNAS_EMM_ERR_INFO_INITIATE_TAU_OPTIMIZATION_STATISTICS_STRU_ALARMID, 16};
STRUCT_DESC g_LNAS_EMM_ERR_INFO_N2L_HO_ABNORMAL_REL_STATISTICS_STRU = { LNAS_EMM_ERR_INFO_N2L_HO_ABNORMAL_REL_STATISTICS_STRU_ALARMID, 20};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_NR_EST_FAIL_EVENT_STRU = { LNAS_IMSA_ERR_INFO_NR_EST_FAIL_EVENT_STRU_ALARMID, 24};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_IMPLICIT_DETACH_EMC_REDIAL_STRU = { LNAS_IMSA_ERR_INFO_IMPLICIT_DETACH_EMC_REDIAL_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_IMSA_ERR_INFO_MEDIA_PDP_LOST_EVENT_STRU = { LNAS_IMSA_ERR_INFO_MEDIA_PDP_LOST_EVENT_STRU_ALARMID, 4};
STRUCT_DESC g_LNAS_ERR_INFO = { LNAS_ERR_INFO_ALARMID_BUTT, 0};
STRUCT_DESC g_WAS_RRC_ACCESS_LONG_CHR_RPT_STRU = { WAS_RRC_ACCESS_LONG_CHR_RPT_STRU_ALARMID, 184};
STRUCT_DESC g_WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = { WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID, 208};
STRUCT_DESC g_WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU = { WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU_ALARMID, 24};
STRUCT_DESC g_WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU = { WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU_ALARMID, 324};
STRUCT_DESC g_WAS_W2W_RESEL_SLOW_CHR_RPT_STRU = { WAS_W2W_RESEL_SLOW_CHR_RPT_STRU_ALARMID, 164};
STRUCT_DESC g_WAS_NET_WORK_FEATURE_CHR_RPT_STRU = { WAS_NET_WORK_FEATURE_CHR_RPT_STRU_ALARMID, 36};
STRUCT_DESC g_WAS_DCH_TRIGGER_CU_CHR_RPT_STRU = { WAS_DCH_TRIGGER_CU_CHR_RPT_STRU_ALARMID, 16};
STRUCT_DESC g_WAS_CS_END_CESSION_NOTIFY_CHR_RPT_STRU = { WAS_CS_END_CESSION_NOTIFY_CHR_RPT_STRU_ALARMID, 248};
STRUCT_DESC g_WAS_ERRORLOG = { WAS_ERRORLOG_ALARMID_BUTT, 0};
STRUCT_DESC g_CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU = { CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU_ALARMID, 16};
STRUCT_DESC g_CTTF_ERRORLOG = { CTTF_ERRORLOG_ALARMID_BUTT, 0};
STRUCT_DESC g_GAS_AP_G2L_RESEL_HIT_STATISTICS_STRU = { GAS_AP_G2L_RESEL_HIT_STATISTICS_STRU_ALARMID, 44};
STRUCT_DESC g_GUNAS_SEARCHED_PLMN_INFO_CHR_RPT_STRU = { GUNAS_SEARCHED_PLMN_INFO_CHR_RPT_STRU_ALARMID, 4};
STRUCT_DESC g_GAS_AP_GSM_AIR_MSG_ABNORMAL_STRU = { GAS_AP_GSM_AIR_MSG_ABNORMAL_STRU_ALARMID, 232};


STRUCT_DESC g_GAS_AP_G2L_PING_PONG_RESTRAIN_RECORD_RPT_STRU = { GAS_AP_G2L_PING_PONG_RESTRAIN_RECORD_RPT_STRU_ALARMID, 164};
STRUCT_DESC g_GUNAS_SILENT_SMS_INFO_CHR_RPT_STRU = { GUNAS_SILENT_SMS_INFO_CHR_RPT_STRU_ALARMID, 28};
STRUCT_DESC g_GUNAS_APS_PS_CALL_ENTITY_CHR_RPT_STRU = { GUNAS_APS_PS_CALL_ENTITY_CHR_RPT_STRU_ALARMID, 360};
STRUCT_DESC g_GUNAS_SRVCC_TIFLAG_ERR_CHR_RPT_STRU = { GUNAS_SRVCC_TIFLAG_ERR_CHR_RPT_STRU_ALARMID, 4};
STRUCT_DESC g_NRRC_CHR_DIRECT_OTA_CHECK_FAIL_STRU = { NRRC_CHR_DIRECT_OTA_CHECK_FAIL_STRU_ALARMID, 768};
STRUCT_DESC g_NRRC_CHR_DIRECT_OUT_OF_SYNC_STRU = { NRRC_CHR_DIRECT_OUT_OF_SYNC_STRU_ALARMID, 36};
STRUCT_DESC g_NRRC_CHR_DIRECT_RA_FAIL_STRU = { NRRC_CHR_DIRECT_RA_FAIL_STRU_ALARMID, 52};
STRUCT_DESC g_NRRC_CHR_DIRECT_RADIO_RES_CHECK_STRU = { NRRC_CHR_DIRECT_RADIO_RES_CHECK_STRU_ALARMID, 196};
STRUCT_DESC g_NRRC_CHR_DIRECT_BAND_CNT_OVER_LMT_STRU = { NRRC_CHR_DIRECT_BAND_CNT_OVER_LMT_STRU_ALARMID, 12};
STRUCT_DESC g_NRRC_CHR_DIRECT_NW_PARA_ABNORMAL_STRU = { NRRC_CHR_DIRECT_NW_PARA_ABNORMAL_STRU_ALARMID, 56};
STRUCT_DESC g_NRRC_CHR_DIRECT_EXTREME_SCENE_STRU = { NRRC_CHR_DIRECT_EXTREME_SCENE_STRU_ALARMID, 12};
STRUCT_DESC g_NRRC_CHR_DIRECT_HPS_RPT_STRU = { NRRC_CHR_DIRECT_HPS_RPT_STRU_ALARMID, 456};
STRUCT_DESC g_NRRC_ERRORLOG = { NRRC_ERRORLOG_ALARMID_BUTT, 0};
STRUCT_DESC g_GAS_AP_GU_PING_PONG_RESTRAIN_RECORD_RPT_STRU = { GAS_AP_GU_PING_PONG_RESTRAIN_RECORD_RPT_STRU_ALARMID, 184};
STRUCT_DESC g_WAS_UL_PINGPONG_RESTRAIN_CHR_RPT_STRU = { WAS_UL_PINGPONG_RESTRAIN_CHR_RPT_STRU_ALARMID, 164};
STRUCT_DESC g_NRRC_CHR_DIRECT_BAD_CELL_STRU = { NRRC_CHR_DIRECT_BAD_CELL_STRU_ALARMID, 28};
STRUCT_DESC g_NRNAS_NRMM_DECODE_MSG_ERR_CHR_RPT_STRU = { NRNAS_NRMM_DECODE_MSG_ERR_CHR_RPT_STRU_ALARMID, 256};
STRUCT_DESC g_NRNAS_NRMM_ESCAPE_CHR_RPT_STRU = { NRNAS_NRMM_ESCAPE_CHR_RPT_STRU_ALARMID, 128};
STRUCT_DESC g_NRNAS_NRMM_REG_ABNORMAL_CHR_RPT_STRU = { NRNAS_NRMM_REG_ABNORMAL_STRU_ALARMID, 332};
STRUCT_DESC g_NRNAS_NRMM_COMPATIBILITY_CHR_RPT_STRU = { NRNAS_NRMM_COMPATIBILITY_CHR_RPT_STRU_ALARMID, 196};
STRUCT_DESC g_NRNAS_NRMM_REG_PROC_CHR_RPT_STRU = { NRNAS_NRMM_REG_PROC_CHR_RPT_STRU_ALARMID, 180};
STRUCT_DESC g_NRNAS_PCF_DECODE_MSG_ERR_CHR_RPT_STRU = { NRNAS_PCF_DECODE_MSG_ERR_CHR_RPT_STRU_ALARMID, 256};
STRUCT_DESC g_NRNAS_NRSM_DECODE_MSG_ERR_CHR_RPT_STRU = { NRNAS_NRSM_DECODE_MSG_ERR_CHR_RPT_STRU_ALARMID, 256};
STRUCT_DESC g_NRNAS_NRSM_COMPATIBILITY_CHR_RPT_STRU = { NRNAS_NRSM_COMPATIBILITY_CHR_RPT_STRU_ALARMID, 196};
STRUCT_DESC g_WAS_RNC_RELOC_CALL_DROP_CHR_RPT_STRU = { WAS_RNC_RELOC_FAIL_CHR_RPT_STRU_ALARMID, 60};
STRUCT_DESC g_GUNAS_READ_6FAD_USIM_FILE_ABNORMAL_CHR_RPT_STRU = { GUNAS_READ_6FAD_USIM_FILE_ABNORMAL_CHR_RPT_STRU_ALARMID, 12};
STRUCT_DESC g_NRRC_CHR_DIRECT_UNEXP_MSG_STRU = { NRRC_CHR_DIRECT_UNEXP_MSG_STRU_ALARMID, 44};
STRUCT_DESC g_NRRC_CHR_DIRECT_CONTINUAL_REEST_STRU = { NRRC_CHR_DIRECT_CONTINUAL_REEST_STRU_ALARMID, 476};
STRUCT_DESC g_NRRC_CHR_DIRECT_N2L_EPSFB_STRU = { NRRC_CHR_DIRECT_N2L_EPSFB_STRU_ALARMID, 20};
STRUCT_DESC g_NRRC_CHR_DIRECT_L2N_REDIR_FAIL_STRU = { NRRC_CHR_DIRECT_L2N_REDIR_FAIL_STRU_ALARMID, 136};

STRUCT_DESC g_NRNAS_NRSM_AIR_MSG_RETRANSMIT_CHR_RPT_STRU = { NRNAS_NRSM_AIR_MSG_RETRANSMIT_CHR_RPT_STRU_ALARMID, 196};
STRUCT_DESC g_GUNAS_AUTH_TYPE_ADAPTATION_CHR_RPT_STRU = { GUNAS_AUTH_TYPE_ADAPTATION_CHR_RPT_STRU_ALARMID, 108};
const STRUCT_DESC * const g_AlarmStructDesc[] =
{
#if (FEATURE_ON == FEATURE_UE_MODE_CDMA)
    &g_CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    &g_CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    &g_CAS_ERRORLOG,
#endif
    &g_GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU,
    &g_GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    &g_GAS_CUSTOM_C1_CELL_CHR_RPT_STRU,
    &g_GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU,
    &g_GAS_ERR_LOG_EVT_GSM_CELL_CALL_TIMES_RPT_STRU,
    &g_GAS_ERRORLOG,
    &g_GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    &g_GUNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU,
    &g_GUNAS_RECEIVE_SMS_IN_ANTI_ATTACK_INFO_CHR_RPT_STRU,
    &g_GUNAS_SMS_ANTI_ATTACK_INFO_CHR_RPT_STRU,
    &g_GUNAS_READ_6FAD_USIM_FILE_ABNORMAL_CHR_RPT_STRU,
    &g_GUCNAS_ERRORLOG,
    &g_TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU,
    &g_TRRC_OOS_INFO_STRU,
    &g_TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU,
    &g_TRRC_CS_CALL_EST_CNF_INFO_STRU,
    &g_TRRC_CS_CALL_CONN_REQ_INFO_STRU,
    &g_TRRC_CS_CALL_AIRMSG_INFO_STRU,
    &g_TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU,
    &g_TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU,
    &g_TRRC_ERRORLOG,
    &g_LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU,
    &g_LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU,
    &g_LRRC_OM_UE_CAP_FALL_REPORT_STRU,
    &g_LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU,
    &g_LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU,
    &g_LRRC_ERRORLOG,
    &g_TLL2_OOS_INFO_STRU,
    &g_LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU,
    &g_TLL2_ERRORLOG,
    &g_LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU,
    &g_LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU,
    &g_LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU,
    &g_LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU,
    &g_LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU,
    &g_LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU,
    &g_LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU,
    &g_LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU,
    &g_LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU,
    &g_LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU,
    &g_LNAS_EMM_ERR_INFO_SMC_FAIL_STRU,
    &g_LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU,
    &g_LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU,
    &g_LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU,
    &g_LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU,
    &g_LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU,
    &g_LNAS_ESM_ERR_INFO_SWITCH_APN_STRU,
    &g_LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU,
    &g_LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU,
    &g_LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU,
    &g_LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU,
    &g_LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU,
    &g_LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU,
    &g_LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU,
    &g_LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU,
    &g_LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU,
    &g_LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU,
    &g_LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU,
    &g_LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU,
    &g_LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU,
    &g_LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU,
    &g_LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU,
    &g_LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU,
    &g_LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU,
    &g_LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU,
    &g_LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU,
    &g_LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU,
    &g_LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU,
    &g_LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU,
    &g_LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU,
    &g_LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU,
    &g_LNAS_EMM_ERR_INFO_RF_OCCUPY_MODEM1_TAU_STRU,
    &g_LNAS_EMM_ERR_INFO_REATTACH_PUNISH_CHR_STRU,
    &g_LNAS_EMM_ERR_INFO_DEEP_GAME_CHR_INFO_STRU,
    &g_LNAS_EMM_ERR_INFO_ATTACH_TAU_FAIL_MAXTIMES_CHR_STRU,
    &g_LNAS_ESM_ERR_INFO_ESM65_CHR_INFO_STRU,
    &g_LNAS_EMM_ERR_INFO_ESCAPE_CHR_INFO_STRU,
    &g_LNAS_ESM_ERR_INFO_LCSLPP_LEN_CHR_INFO_STRU,
    &g_LNAS_ESM_ERR_INFO_AIR_COMPATI_CHR_INFO_STRU,
    &g_LNAS_ERABM_ERR_INFO_BEAR_ACT_WITHOUT_DRB_INFO_STRU,
    &g_LNAS_EMM_ERR_INFO_HO_WITHIN_TAU_PROCESS_INFO_STRU,
    &g_LNAS_LMM_OM_DL_NASCOUNT_ERR_CHR_STRU,
    &g_LNAS_ESM_ERR_INFO_BEARER_STATUS_INCONSISTENT_STRU,
    &g_LNAS_EMM_ERR_INFO_REPEATEDLY_CONN_RECOVER_TAU_EFFECT_STRU,
    &g_LNAS_IMSA_ERR_INFO_RELEASE_SIGNAL_BEAR_STRU,
    &g_LNAS_EMM_ERR_INFO_ESCAPE_DESCEND_CAP_INFO_STRU,
    &g_LNAS_EMM_ERR_INFO_ROBUST_OPTIMIZATION_STATISTICS_INFO_STRU,
    &g_LNAS_ESM_ERR_INFO_CHANGE_NULL_APN_OPT_STRU,
    &g_LNAS_EMM_ERR_INFO_LRRC_SMC_FAIL_CHR,
    &g_LNAS_ESM_ERR_INFO_5G_ESCAPE_DESCEND_CAP_INFO_STRU,
    &g_LNAS_EMM_ERR_INFO_COMPATIBILITY_STRU,
    &g_LNAS_ESM_ERR_INFO_ESM_STATUS_NOT_EQ_LMM_STRU,
    &g_LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_OPTIMIZATION_STATISTICS_STRU,
    &g_LNAS_EMM_ERR_INFO_INITIATE_TAU_OPTIMIZATION_STATISTICS_STRU,
    &g_LNAS_EMM_ERR_INFO_N2L_HO_ABNORMAL_REL_STATISTICS_STRU,
    &g_LNAS_IMSA_ERR_INFO_NR_EST_FAIL_EVENT_STRU,
    &g_LNAS_IMSA_ERR_INFO_IMPLICIT_DETACH_EMC_REDIAL_STRU,
    &g_LNAS_IMSA_ERR_INFO_MEDIA_PDP_LOST_EVENT_STRU,
    &g_LNAS_ERR_INFO,
    &g_WAS_RRC_ACCESS_LONG_CHR_RPT_STRU,
    &g_WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    &g_WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU,
    &g_WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU,
    &g_WAS_W2W_RESEL_SLOW_CHR_RPT_STRU,
    &g_WAS_NET_WORK_FEATURE_CHR_RPT_STRU,
    &g_WAS_DCH_TRIGGER_CU_CHR_RPT_STRU,
    &g_WAS_CS_END_CESSION_NOTIFY_CHR_RPT_STRU,
    &g_WAS_ERRORLOG,
    &g_CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU,
    &g_CTTF_ERRORLOG,
    &g_GAS_AP_G2L_RESEL_HIT_STATISTICS_STRU,
    &g_GUNAS_SEARCHED_PLMN_INFO_CHR_RPT_STRU,
    &g_GAS_AP_GSM_AIR_MSG_ABNORMAL_STRU,
    &g_GAS_AP_G2L_PING_PONG_RESTRAIN_RECORD_RPT_STRU,
    &g_GUNAS_SILENT_SMS_INFO_CHR_RPT_STRU,
    &g_GUNAS_APS_PS_CALL_ENTITY_CHR_RPT_STRU,
    &g_GUNAS_SRVCC_TIFLAG_ERR_CHR_RPT_STRU,
    &g_NRRC_CHR_DIRECT_OTA_CHECK_FAIL_STRU,
    &g_NRRC_CHR_DIRECT_OUT_OF_SYNC_STRU,
    &g_NRRC_CHR_DIRECT_RA_FAIL_STRU,
    &g_NRRC_CHR_DIRECT_RADIO_RES_CHECK_STRU,
    &g_NRRC_CHR_DIRECT_BAND_CNT_OVER_LMT_STRU,
    &g_NRRC_CHR_DIRECT_NW_PARA_ABNORMAL_STRU,
    &g_NRRC_CHR_DIRECT_EXTREME_SCENE_STRU,
    &g_NRRC_CHR_DIRECT_HPS_RPT_STRU,
    &g_NRRC_CHR_DIRECT_L2N_REDIR_FAIL_STRU,
    &g_NRRC_ERRORLOG,
    &g_GAS_AP_GU_PING_PONG_RESTRAIN_RECORD_RPT_STRU,
    &g_WAS_UL_PINGPONG_RESTRAIN_CHR_RPT_STRU,
    &g_NRRC_CHR_DIRECT_BAD_CELL_STRU,
    &g_NRNAS_NRMM_DECODE_MSG_ERR_CHR_RPT_STRU,
    &g_NRNAS_NRMM_ESCAPE_CHR_RPT_STRU,
    &g_NRNAS_NRMM_REG_ABNORMAL_CHR_RPT_STRU,
    &g_NRNAS_NRMM_COMPATIBILITY_CHR_RPT_STRU,
    &g_NRNAS_NRMM_REG_PROC_CHR_RPT_STRU,
    &g_NRNAS_PCF_DECODE_MSG_ERR_CHR_RPT_STRU,
    &g_NRNAS_NRSM_DECODE_MSG_ERR_CHR_RPT_STRU,
    &g_NRNAS_NRSM_COMPATIBILITY_CHR_RPT_STRU,
    &g_WAS_RNC_RELOC_CALL_DROP_CHR_RPT_STRU,
    &g_NRNAS_NRSM_AIR_MSG_RETRANSMIT_CHR_RPT_STRU,
    &g_NRRC_CHR_DIRECT_UNEXP_MSG_STRU,
    &g_GUNAS_AUTH_TYPE_ADAPTATION_CHR_RPT_STRU,
};
const VOS_UINT32 g_AlarmStructDescCount = sizeof(g_AlarmStructDesc) / sizeof(g_AlarmStructDesc[0]);
