#ifndef __HI_TSENSOR_H__
#define __HI_TSENSOR_H__ 
#define THERMAL_PROTECT 
#define THERMAL_LOW_TEM_STARTUP 
#define MDM5G_PM_CTRL 0xF400C000
#define MDM5G_PM_CTRL_OFFSET 0x014
#define PMU_VOL_IDX0_OFFSET 0x100
#define CURR_PMU_VOL0_OFFSET 0x110
#define TSENSOR_TEMP_PRO_VOLT 0x15a
#define TSENSOR_TEMP_PRO_CHECK_VOLT 0x5a
#define TSENSOR_TEMP_PRO_REVOKE_VOLT 0x100
#define THERMAL_SCTRL_LR_ADDR_RESERVED 0xE0200000
#define THERMAL_SCTRL_LR_OFFSET_RESERVED 0x484
#define THERMAL_SCTRL_NR_ADDR_RESERVED 0xF4001000
#define THERMAL_SCTRL_NR_OFFSET_RESERVED 0x41C
#define LTEMP_PRO_IN_VOL 850
#define LTEMP_PRO_OUT_VOL 0
enum tsensor_core_id {
    ACPU = 0,
    MDM4G,
    MDM5G_SOC,
    TSENSOR_CORE_ID_BUTT
};
enum tsensor_id {
    BBA = 0,
    MDM5G_BBP,
    MDM5G_BBP_1,
    MDM5G,
    MDM4G_SOC,
    MDM4G_BBP,
    TSENSOR_ID_BUTT
};
#endif
