# MD5: 46e21380316d5c735a92327952dbdca9
set(CFG_BBP_MASTER_NONE 0) 

set(CFG_BBP_MASTER_VER1 1) 

set(CFG_BBP_MASTER_VER2 2) 

set(CFG_BBP_MASTER_VER3 3) 

set(CFG_BBP_MASTER_VER4 4) 

set(CFG_BBP_MASTER_VER5 5) 

set(CFG_BBP_MASTER_VER6 6) 

set(CFG_FEATURE_BBP_MASTER_VER (BBP_MASTER_VER5)) 

set(CFG_FEATURE_POWER_TIMER FEATURE_ON) 

set(CFG_FEATURE_UE_UICC_MULTI_APP_SUPPORT FEATURE_ON) 

set(CFG_FEATURE_VSIM FEATURE_ON) 

set(CFG_FEATURE_GUC_BBP_TRIG FEATURE_ON) 

set(CFG_FEATURE_CSIM_NONCHECK FEATURE_OFF) 

set(CFG_FEATURE_GUC_BBP_TRIG_NEWVERSION FEATURE_ON) 

set(CFG_FEATURE_VOS_REDUCE_MEM_CFG FEATURE_OFF) 

set(CFG_FEATURE_RTC_TIMER_DBG FEATURE_ON) 

set(CFG_FEATURE_PHONE_SC FEATURE_ON) 

set(CFG_FEATURE_PHONE_USIM FEATURE_ON) 

set(CFG_FEATURE_SC_CUST FEATURE_OFF) 

set(CFG_FEATURE_SC_PUBLIC_DATA_KEY_UPDATE FEATURE_OFF) 

set(CFG_FEATURE_PIN_CRYPTO_PROTECT FEATURE_ON) 

set(CFG_FEATURE_MBB_ACORE_64BIT_ENABLE FEATURE_OFF) 

set(CFG_FEATURE_SC_NETWORK_UPDATE FEATURE_OFF) 

set(CFG_FEATURE_SC_RSA_PADDING_UPDATE FEATURE_OFF) 

set(CFG_FEATURE_SC_PBKDF2_UPDATE FEATURE_ON) 

set(CFG_FEATURE_VSIM_ICC_SEC_CHANNEL FEATURE_ON) 

set(CFG_FEATURE_BOSTON_AFTER_FEATURE FEATURE_ON) 

set(CFG_FEATURE_XSIM FEATURE_OFF) 

set(CFG_FEATURE_SCI_SWITCH_OPTIMIZE FEATURE_ON) 

set(CFG_FEATURE_VOS_18H_TIMER FEATURE_ON) 

set(CFG_FEATURE_SET_C1C2_VALUE FEATURE_ON) 

set(CFG_FEATURE_DEEP_SLEEP_ANTEN_DETECT FEATURE_OFF) 

set(CFG_PAM_ENG_ENABLED NO) 

set(CFG_PAM_CT_ENABLED NO) 

set(CFG_PAM_BT_ENABLED NO) 

set(CFG_FEATURE_SINGLEMODEM_DUALSLOT FEATURE_OFF) 

