if(NOT extra_modem)

include("${CMAKE_CURRENT_LIST_DIR}/product_config_drv.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_pam.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucas.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucnas.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_easyrf.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucphy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_tlps.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_tlphy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_lr_phy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_nphy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_audio.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_tool.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_nrps.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_version.cmake")

else()

include("${CMAKE_CURRENT_LIST_DIR}/product_config_drv_extra.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_pam.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucas.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucnas_extra.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_easyrf.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucphy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_tlps.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_tlphy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_lr_phy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_nphy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_audio.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_tool.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_nrps.cmake")


endif()
