# MD5: a67441da74b56a181708501cc081b640
set(CFG_PRODUCT_CONTROL_VERSION      		 "141") 

set(CFG_PRODUCT_HISILICON_VERSION kirin990_cs2) 

set(CFG_PRODUCT_DIFF_NV_FILTER          	 kirin990_cs2_udp) 

set(CFG_PRODUCT_NV_FILE_MAX_SIZE           	 binfileLimitSize "10000") 

set(CFG_PRODUCT_NV_BIN_MODEM_NUNBER       	 bin_modem_number "3") 

set(CFG_PRODUCT_COMMON_NV_FILE_FORMAT		 common_nv_file_format "1") 

set(CFG_PRODUCT_XML_FOLDER_HIONE			 1) 

set(CFG_PRODUCT_NV_COMPRESS             	 compress_nv_file "1") 

set(CFG_PRODUCT_NV_XNV_PDT_VERSION        	 hi9500) 

set(CFG_PRODUCT_NV_PARSE_CUSTOMIZE			 parse_customize "1") 

set(CFG_PRODUCT_VERSION_AFTER_B5000			 1) 

set(CFG_PRODUCT_COMMON_NV_INHERIT_BY_PRODUCT		 true) 

set(CFG_PRODUCT_SPLIT_NV_BUILD true) 

set(CFG_PRODUCT_NCFG_DISTINGUISH_MODEM_FEATURE_ON YES) 

set(CFG_PRODUCT_NCFG_INDEPENDENT_FEATURE_NV YES) 

set(CFG_DIAG_SEC_TOOLS YES) 

if(${CFG_RF0_TYPE_DV200} MATCHES "FEATURE_ON")
set(CFG_RF_NV_PLATFORM_DPV200				 _dpv200) 

endif()
