#ifndef __LOADMONITOR_PLAT_H__
#define __LOADMONITOR_PLAT_H__ 
#define SHARED_MEMORY_SIZE (1024 * 3)
#define MAX_SENSOR_NUM 32
#define MONITOR_STAT_NUM 3
#define MAX_PERI_MONITOR0_DEVICE 31
#define MONITOR0_IP_MASK 0x7FFFFFFF
#define MAX_PERI_MONITOR1_DEVICE 23
#define MONITOR1_IP_MASK 0xFFC307FF
#define MAX_PERI_MONITOR2_DEVICE 5
#define MONITOR2_IP_MASK 0xF80
#define MAX_MEDIA_MONITOR0_DEVICE 26
#define MEDIA_MONITOR0_IP_MASK 0x0FFFFFFC
#define MAX_MEDIA_MONITOR1_DEVICE 32
#define MEDIA_MONITOR1_IP_MASK 0xFFFFFFFF
#ifndef CONFIG_LIBLINUX
#define MAX_MONITOR_IP_DEVICE_AO 27
#define AO_MONITOR0_IP_MASK 0xFFFE0FFF
#endif
#define MAX_PERI_MONITOR_DEVICE (MAX_PERI_MONITOR0_DEVICE + MAX_PERI_MONITOR1_DEVICE + MAX_PERI_MONITOR2_DEVICE)
#define MAX_MEDIA_MONITOR_DEVICE (MAX_MEDIA_MONITOR0_DEVICE + MAX_MEDIA_MONITOR1_DEVICE)
#define MAX_PERI_AND_MEDIA_MONITOR_DEVICE (MAX_PERI_MONITOR_DEVICE + MAX_MEDIA_MONITOR_DEVICE)
#define MAX_MONITOR_IP_DEVICE (MAX_PERI_MONITOR_DEVICE + MAX_MEDIA_MONITOR_DEVICE)
#ifndef CONFIG_LIBLINUX
#define CS_MAX_AO_INDEX (MAX_MONITOR_IP_DEVICE_AO * (MONITOR_STAT_NUM + 1))
#else
#define CS_MAX_AO_INDEX 0
#endif
#define CS_MAX_PERI_INDEX (MAX_PERI_AND_MEDIA_MONITOR_DEVICE * MONITOR_STAT_NUM)
#define U32_MAX_DIGIT 10
#define U64_MAX_DIGIT 20
#define LOADMONITOR_BUFF_SIZE (CS_MAX_AO_INDEX*(U64_MAX_DIGIT + 1) + CS_MAX_PERI_INDEX*(U32_MAX_DIGIT + 1) + 1)
#endif
